version: "3.9"

services:

  db:
      image: postgis/postgis:15-3.3
      restart: on-failure
      volumes:
        - postgres_data:/var/lib/postgresql
      env_file:
        - .env_docker
      expose:
        - "5432"
      networks:
        - leaflet_project

  web:
    build: .
    ports:
      - "8008:8008"
    env_file:
      - .env_docker
    depends_on:
      - db
    networks:
      - leaflet_project

  graphql-engine:
    image: hasura/graphql-engine:v2.2.0
    ports:
      - "8081:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://plot_hasura_base_user:plot_hasura_base_password@plot_hasura_base_postgres:5432/plot_hasura_base
      HASURA_GRAPHQL_AGRO_BASE_DATABASE_URL: postgres://agro_base_user:agro_base_password@agro_base_postgres:5432/agro_base
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
    command:
      - graphql-engine
      - serve


networks:
   leaflet_project:
     driver: bridge

volumes:
  postgres_data: