# Generated by Django 4.1.6 on 2023-02-06 06:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=32140, verbose_name='Координаты района'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=32140, verbose_name='Координаты поля'),
        ),
        migrations.AlterField(
            model_name='region',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=32140, verbose_name='Координаты региона'),
        ),
    ]
