# Generated by Django 4.1.6 on 2023-02-06 06:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название района')),
                ('coordinates', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='SRID=32140;POINT(954158.1 4215137.1)')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('coordinates', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='SRID=32140;POINT(954158.1 4215137.1)')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
                'db_table': 'plots',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название региона')),
                ('coordinates', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='SRID=32140;POINT(954158.1 4215137.1)')),
                ('areas', models.ManyToManyField(related_name='region_areas', to='webapp.area', verbose_name='Районы')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='plots',
            field=models.ManyToManyField(related_name='area_plots', to='webapp.plot', verbose_name='Поля'),
        ),
    ]
