# Generated by Django 4.1.6 on 2023-02-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_area_coordinates_alter_plot_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='plots',
        ),
        migrations.RemoveField(
            model_name='region',
            name='areas',
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='area_region', to='webapp.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='plot',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plot_area', to='webapp.area', verbose_name='Район'),
        ),
    ]
